title: Jumakhan Rahyab
description: Math, Entrepreneurship, and Innovation Ecosystems
theme: jekyll-theme-minimal
markdown: kramdown

author:
  name: Jumakhan Rahyab

show_downloads: false

{% include footer.html %}
